### ISSUE TITLE
[v3.1.0] RulesEngine does not update the compiled rules atomically.

### ISSUE THREAD

**Issue by AshishPrasad** [microsoft/RulesEngine#158]
Starting this thread to discuss the synchronization issue due to the compiled rule not updated atomically.

### Current Workaround 
We need to perform:
1. [RulesEngine.RemoveWorkflow(string workflowName)](https://github.com/microsoft/RulesEngine/blob/v3.1.0/src/RulesEngine/RulesEngine.cs#L190) and
2. [RulesEngine.AddWorkflow(WorkflowRules[] workflowRules)](https://github.com/microsoft/RulesEngine/blob/v3.1.0/src/RulesEngine/RulesEngine.cs#L156) in sequence to clear the compiled rules (`_compileRules`) in [RulesCache.cs](https://github.com/microsoft/RulesEngine/blob/v3.1.0/src/RulesEngine/RulesCache.cs#L16). 
3. The compiled rules are then refreshed when we call `RulesEngine.ExecuteAllRulesAsync(string workflowName, params RuleParameter[] ruleParams)`(see [[1]](https://github.com/microsoft/RulesEngine/blob/v3.1.0/src/RulesEngine/RulesEngine.cs#L106), [[2]](https://github.com/microsoft/RulesEngine/blob/v3.1.0/src/RulesEngine/RulesEngine.cs#L209), [[3]](https://github.com/microsoft/RulesEngine/blob/v3.1.0/src/RulesEngine/RulesEngine.cs#L247)).

### Synchronization Issue
Caller needs to synchronize the incoming requests for a worflow name by [SemaphoreSlim](https://docs.microsoft.com/en-us/dotnet/api/system.threading.semaphore?view=net-5.0) lock (or equivalent) when they need to execute rules via the above three operations otherwise workflow rules may not be executed say if one of the requests is trying to `ExecuteAllRulesAsync` while the other request is `RulesEngine.RemoveWorkflow`.

### Proposed
Provide an atomic way to update the (`_compileRules`) in [RulesCache.cs](https://github.com/microsoft/RulesEngine/blob/v3.1.0/src/RulesEngine/RulesCache.cs#L16) by a new method `RulesEngine.AddOrUpdateWorkflowRules(WorkflowRules[] workflowRules, params Type[] type)` .

**Comment by AshishPrasad** [comment]
@abbasc52 - can you please check this issue and provide your suggestions.

**Comment by abbasc52** [comment]
@AshishPrasad Thanks for explaining the issue so clearly!
From what I understand, the issue arrises due to `ExecuteAllRulesAsync` being called before we can add the rule back after removing it.

Adding a method `AddOrUpdateWorkflowRules` makes sense but I would prefer it to be not clubbed with compiled cache refresh due to the following reason:

- RulesEngine supports dynamic input, in that case users would not be able to provide the types for compilation
- Even when we make `AddOrUpdateWorkflowRules` update compiled rules, we would still need to handle concurrency when some other request calls `ExecuteAllRulesAsync`

I would suggest we make `RulesEngine.AddOrUpdateWorkflowRules(WorkflowRules[] workflowRules)` atomic, and let rules get compiled again when we call `ExecuteAllRulesAsync` while ensuring we take care of concurrency issue

Please do let me know your thoughts on this

**Comment by abbasc52** [comment]
@AshishPrasad Thanks for explaining the issue so clearly!
From what I understand, the issue arrises due to `ExecuteAllRulesAsync` being called before we can add the rule back after removing it.

Adding a method `AddOrUpdateWorkflowRules` makes sense but I would prefer it to be not be clubbed with compiled cache refresh due to the following reason:

- RulesEngine supports dynamic input, in that case users would not be able to provide the types for compilation
- Even when we make `AddOrUpdateWorkflowRules` update compiled rules, we would still need to handle concurrency when some other request calls `ExecuteAllRulesAsync`

I would suggest we make `RulesEngine.AddOrUpdateWorkflowRules(WorkflowRules[] workflowRules)` atomic, and let rules get compiled again when we call `ExecuteAllRulesAsync` while ensuring we take care of concurrency issue

Please do let me know your thoughts on this

**Comment by AshishPrasad** [comment]
@abbasc52 - Thank you for quickly reviewing and providing your thoughts on the issue.

> the issue arrises due to ExecuteAllRulesAsync being called before we can add the rule back after removing it.

Yes, that's why as of v3.1.0, caller has to synchronize `RemoveWorkflow`, `AddWorkflow` and `ExecuteAllRulesAsync` to execute refreshed rules for a workflow.

> we make RulesEngine.AddOrUpdateWorkflowRules(WorkflowRules[] workflowRules) atomic, and let rules get compiled again when we call ExecuteAllRulesAsync.

+1 for making `RulesEngine.AddOrUpdateWorkflowRules(WorkflowRules[] workflowRules)` atomically update the `_rulesCache` and clearing `_compileRules`  in `RulesCache.cs` so that `RulesEngine.ExecuteAllRulesAsync` refreshes the `_compileRules` and not run the old compiled rules.

> while ensuring we take care of concurrency issue

+1, if callers do not need to synchronize the below two operations (1, 2) to refresh and execute the new rules, it would incur less CPU usage by avoiding Semaphore or other synchronization constructs.

1. `RulesEngine.AddOrUpdateWorkflowRules` and
2. `RulesEngine.ExecuteAllRulesAsync`.

**Comment by AshishPrasad** [comment]
> while ensuring we take care of concurrency issue

**Probable solution**: We can add a timestamp (`DateTime.UtcNow.Ticks`) field to the `ConcurrentDictionary` values of `_compileRules` and `_workflowRules`.

Now, the following sequence should execute refreshed rules while also taking care of concurrent requests:

1. `RulesEngine.AddOrUpdateWorkflowRules` => `_workflowRules` will be updated with the new rules and updated timestamp.  The previous requests continue to execute existing `_compileRules`.
2. `RulesEngine.ExecuteAllRulesAsync` => The [RegisterRule](https://github.com/microsoft/RulesEngine/blob/v3.1.0/src/RulesEngine/RulesEngine.cs#L233) will `AddOrUpdateCompiledRule` if either `!_rulesCache.ContainsCompiledRules(compileRulesKey) || _rulesCache.ContainsOutdatedCompiledRules(compileRulesKey, workflowName)`. This will ensure the new concurrent requests now compile new rules from updated `_workflowRules` and execute them.

@abbasc52 - let me know if this looks good.

**Comment by AshishPrasad** [comment]
@abbasc52 - wanted to check the release cadence of the new versions for the library so that we can update to the `AddOrUpdateWorkflow` which is introduced by the recently merged [PR](https://github.com/microsoft/RulesEngine/pull/159).

**Comment by abbasc52** [comment]
We don't have any strict cadence, as for this new change, we should be good to release by 9th or 10th June

**Comment by abbasc52** [comment]
this has been fixed in v3.2.0
