### ISSUE TITLE
Using ReSettings doesn't appear to work

### ISSUE THREAD

**Issue by bjsapir** [microsoft/RulesEngine#39]
I have coded a custom class like the wiki example provided for using ReSettings and I get an exception:
No applicable method 'LengthGreaterThan' exists in type 'Utils'

 I'm coding in VisualStudio & C#. Not sure how to get it to work.

The class is:
namespace ValidationFunction
{
    public static class Utils
    {
        public static bool LengthGreaterThan(string s, int len)
        {
            return str.Length > len;
        }
    }
}

It's setup as
            var reSettingsWithCustomTypes = new ReSettings { CustomTypes = new Type[] { typeof(Utils) } };
            var bre = new RulesEngine.RulesEngine(workflowRules.ToArray(), null, reSettingsWithCustomTypes);

The rule contains: "Expression": "input1.CompanyName != null && Utils.LengthGreaterThan(input1.CompanyName, 6) == true"

**Comment by bjsapir** [comment]
It may have been my input but after playing
with it more I got it to work.

Thanks!

**Comment by abbasc52** [comment]
Hi @bjsapir , it is possible that it happened because your input is a dynamic object and the property you tried accessing was null.
It has something to do with how we convert Dynamic objects to typed objects. 
In case of null, we assume the type as `object`.
In case you want to handle null in inputs you can modify you Utils class as follows:
```csharp
public static class Utils
{
   public static bool LengthGreaterThan(object s, int len)
   {
       if(s is string){
           return (string)s.Length > len
       }
   }
}
```

or you could try typecasting it in the expression before passing it
`"Expression": "input1.CompanyName != null && Utils.LengthGreaterThan((string)(input1.CompanyName), 6) == true" `

**Comment by bjsapir** [comment]
I’ll have an opportunity to test more next week
to confirm. thank-you for the suggestions

**Comment by abbasc52** [comment]
@bjsapir we have added test case for typecasting

https://github.com/microsoft/RulesEngine/blob/6b66162e561b5447c4c3500f167f8823c3c7cbbe/test/RulesEngine.UnitTest/TestData/rules5.json#L10

https://github.com/microsoft/RulesEngine/blob/6b66162e561b5447c4c3500f167f8823c3c7cbbe/test/RulesEngine.UnitTest/BusinessRuleEngineTest.cs#L236-L256

**Comment by abbasc52** [comment]
@bjsapir Closing this issue. Feel free to reopen it if you still face any problems.
