### ISSUE TITLE
Best way to deal with lists of objects in the data

### ISSUE THREAD

**Issue by samholder** [microsoft/RulesEngine#430]
Imagine I have input data that looks like this:

```
{
       "prop1": 10,
       "prop2": "somevalue",
       "listprop": [
            {
                  "prop3":100
            },
            {
                  "prop3":200
            },
            {
                  "prop3":300
            }
    ]
}
```

I want to be able to write an expression like:

`myThing.listprop.Any(x=>x.prop3>200)`

but this doesn't work with the expressions by default, I think because the extension methods are not in the right namespace.

I've tried to write a utility class to inject, but I'm struggling to get the lamda expression to work.  and I end up with an error message like:

> Exception while parsing expression `ListUtils.Any(myThing.listprop, x=>x.prop3==25)==true` - Unknown identifier 'x'

Is dealing with collections possible in rules engine?

Am I missing some way of doing this?

**Comment by abbasc52** [comment]
@samholder `myThing.listprop.Any(x=>x.prop3>200)` should work but due to limitation in the compiler, it cannot detect it as lambda, as a workaround, you need to define proper spaces before and after `=>`
e.g. `myThing.listprop.Any(x => x.prop3>200)`
It also supports directly using props as you mentioned.
