### ISSUE TITLE
Vulnerability in System.Linq.Dynamic.Core - CVE-2023-32571

### ISSUE THREAD

**Issue by boeschti** [microsoft/RulesEngine#495]
Hi,

The package System.Linq.Dynamic.Core used in the latest version has a vulnerability and needs to be updated to at least 1.3.0

**Comment by boeschti** [comment]
![image](https://github.com/microsoft/RulesEngine/assets/33869728/3ec0bdf4-b183-4b07-9310-f1c204083145)

**Comment by abbasc52** [comment]
I am working on a PR to fix this. will update soon

**Comment by solutions-simplified** [comment]
I recently upgrade from 4.0.0 to 5.0.1. I am getting errors across the board and it looks like it's related to this. In my Utils class I have static methods that take in strongly typed objects (see below). I keep getting a Common Language Runtime error when these rules execute. It appears to be because it can't actually execute my method in the Utils class. Suggestions?

My expression: customers.Where(CreatedDate >= CreatedFilter).Where(Utils.IsExistingEmail(Emails, Customer)).Count() < threshold	

    public static class Utils
    {
        public static bool IsExistingEmail(IList<Email> emails, Customer customer)
        {
            if (emails is null || customer is null)
                return false;
				
				
			return emails.Any(x => x.Address.Contains(customer.Email);
        }
    }

**Comment by solutions-simplified** [comment]
I review the Wiki but the examples shown with Utils is simple string parameters, but do not see any examples with extension methods utilizing strongly typed objects
