### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by niuzheng168** [microsoft/RulesEngine#62]
I did some performance test on nestedinputdemo:
```            
            foreach (var workflow in workflowRules)
            {
                List<RuleResultTree> resultList = bre.ExecuteRule(workflow.WorkflowName, nestedInput);
            }

            Stopwatch sw = new Stopwatch();
            sw.Start();

            for (int i = 0; i < 10000; i++)
            {
                foreach (var workflow in workflowRules)
                {
                    List<RuleResultTree> resultList = bre.ExecuteRule(workflow.WorkflowName, nestedInput);
                }
            }

            sw.Stop();
            Console.WriteLine($"{sw.ElapsedMilliseconds}");
```

~~it shows it need 40ms to finish the 30000 times rule execution.~~
correction:  it shows it need **120**ms to finish the 30000 times rule execution ( 40ms is 10000 times ).
Is there any way to make it faster?

**Comment by KoalaBear84** [comment]
I'm not the developer! My user experience 😀

Faster? 😯

We had issues that it sometimes took 30-50 seconds or so. Although we couldnt find what caused it (we guess it was because all of the external things). But that was before we 'cached' the RuleEngine instance itself. After we cached it, it dropped to 160ms or so. But that is including some (external) startup code.

Remember that this is (I guess) all done with reflection and more dynamic code. So it will always be slower than hardcoded checks.

So 40 ms for 30.000 runs seems very nice (to me).

**Comment by abbasc52** [comment]
@niuzheng168 could you share more details on which version of RulesEngine are you using?

**Comment by niuzheng168** [comment]
> @niuzheng168 could you share more details on which version of RulesEngine are you using?

I am using 2.1.4.

I think the main time cost happened on 
`var resultTree = compiledRule.Rule.DynamicInvoke(new List<object>(inputs) { new RuleInput() }.ToArray()) as RuleResultTree;`
as DynamicInvoke could do many reflection work.

In my scenario, my input type is fixed, do you  think supporing Generic Type like CompiledRule<T1, T2> can fix this issue?

**Comment by abbasc52** [comment]
@niuzheng168 can you try v3.0.0-preview.2 ? It has upto 35% performance improvements
